# Generated by Django 6.1 on 2026-08-29 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtletaEscalado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta_id_cartola', models.PositiveIntegerField(help_text='ID do atleta -> Cartola FC')),
                ('apelido', models.CharField(max_length=100)),
                ('clube', models.CharField(blank=True, max_length=100)),
                ('posicao', models.CharField(blank=True, max_length=50)),
                ('preco_cartoletas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pontos_num', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('foto_url', models.URLField(blank=True)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='app.time')),
            ],
            options={
                'ordering': ['-adicionado_em'],
                'unique_together': {('time', 'atleta_id_cartola')},
            },
        ),
    ]
